name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Kodun depodan çekilmesi
    - name: Checkout code
      uses: actions/checkout@v3

    # Python ortamının kurulması
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Gerekli bağımlılıkların yüklenmesi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Testlerin çalıştırılması
    - name: Run tests
      run: pytest test_app.py
