name: Python CI

on:
  push:
    branches:
      - main  # Ana dalda yapılan her değişiklikte pipeline çalışır
  pull_request:
    branches:
      - main  # Ana dala açılan pull request'lerde pipeline çalışır

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Depoyu çek
      - name: Checkout code
        uses: actions/checkout@v3

      # Python'u kur
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Bağımlılıkları yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Testleri çalıştır
      - name: Run tests
        run: python -m unittest discover -s . -p "test_*.py"
